version: '3.1'

services:
  api:
    container_name: backend_app_owasp_demo_api
    image: backend_app_owasp_demo_api
    build: ./api
    command: npm run start
    env_file: .env
    restart: always
    ports:
    - "${PORT}:${PORT}"

  users:
    container_name: backend_app_owasp_demo_users
    image: backend_app_owasp_demo_users
    build: ./users
    command: npm run start
    env_file: .env
  catalogs:
    container_name: backend_app_owasp_demo_catalogs
    image: backend_app_owasp_demo_catalogs
    build: ./catalogs
    command: npm run start
    env_file: .env
  sessions:
    container_name: backend_app_owasp_demo_sessions
    image: backend_app_owasp_demo_sessions
    build: ./sessions
    command: npm run start
    env_file: .env
  db:
    container_name: db_owasp_demo
    image: db_owasp_demo
    build: ./database
    env_file: .env
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
    driver: "local"
